package installer

import (
	"path/filepath"

	"github.com/lunar-debian/wsl-dev-setup/internal/utils"
)

type ShellConfigStep struct{}

func NewShellConfigStep() *ShellConfigStep {
	return &ShellConfigStep{}
}

func (s *ShellConfigStep) Name() string {
	return "shell_config"
}

func (s *ShellConfigStep) Check(ctx *Context) (bool, error) {
	files := []string{
		filepath.Join(ctx.Env.HomeDir, ".zshrc"),
		filepath.Join(ctx.Env.HomeDir, ".p10k.zsh"),
		filepath.Join(ctx.Env.HomeDir, ".gitconfig"),
	}
	for _, f := range files {
		if !utils.FileExists(f) {
			return false, nil
		}
	}
	return true, nil
}

func (s *ShellConfigStep) Run(ctx *Context) error {
	if ctx.DryRun {
		ctx.Logger.Info("[DRY RUN] Would write shell configuration files")
		return nil
	}

	ctx.Logger.Info("Writing shell configuration...")

	if err := s.writeZshrc(ctx); err != nil {
		return err
	}
	if err := s.writeP10k(ctx); err != nil {
		return err
	}
	if err := s.writeGitconfig(ctx); err != nil {
		return err
	}

	return nil
}

func (s *ShellConfigStep) Rollback(ctx *Context) error {
	if ctx.DryRun {
		return nil
	}

	files := []string{
		filepath.Join(ctx.Env.HomeDir, ".zshrc"),
		filepath.Join(ctx.Env.HomeDir, ".p10k.zsh"),
		filepath.Join(ctx.Env.HomeDir, ".gitconfig"),
	}

	for _, f := range files {
		ctx.Backup.Backup(f)
	}

	ctx.Backup.RestoreAll()
	return nil
}

func (s *ShellConfigStep) writeZshrc(ctx *Context) error {
	path := filepath.Join(ctx.Env.HomeDir, ".zshrc")
	ctx.Backup.Backup(path)

	content := zshrcTemplate
	return utils.WriteFileAtomic(path, content)
}

func (s *ShellConfigStep) writeP10k(ctx *Context) error {
	path := filepath.Join(ctx.Env.HomeDir, ".p10k.zsh")
	ctx.Backup.Backup(path)

	var content string
	switch ctx.Config.Style {
	case "classic":
		content = p10kClassicTemplate
	case "rainbow":
		content = p10kRainbowTemplate
	default:
		content = p10kLeanTemplate
	}

	return utils.WriteFileAtomic(path, content)
}

func (s *ShellConfigStep) writeGitconfig(ctx *Context) error {
	path := filepath.Join(ctx.Env.HomeDir, ".gitconfig")
	ctx.Backup.Backup(path)

	data := struct {
		User  string
		Email string
	}{
		User:  ctx.Env.User,
		Email: ctx.Env.User + "@example.com",
	}

	content, err := utils.RenderTemplate(ctx.Logger, gitconfigTemplate, data)
	if err != nil {
		return err
	}
	return utils.WriteFileAtomic(path, content)
}

const zshrcTemplate = `# ~/.zshrc - Generated by wsl-dev-setup
# Oh My Zsh installation
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
  git
  docker
  npm
  volta
  kubectl
  command-not-found
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-completions
  fzf-tab
  zsh-vi-mode
)

source $ZSH/oh-my-zsh.sh

# History
HISTSIZE=50000
SAVEHIST=50000
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_SPACE

# Keybindings
bindkey -v
bindkey '^R' fzf-history-widget
bindkey '^F' fzf-file-widget
bindkey '^[c' fzf-cd-widget
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Modern aliases
alias ls='eza --icons --group-directories-first'
alias ll='eza -la --icons --group-directories-first'
alias lt='eza --tree --icons'
alias cat='bat --style=auto'
alias find='fd'
alias grep='rg'
alias top='btop'
alias cd='z'
alias lg='lazygit'
alias diff='delta'

# Functions
mkcd() { mkdir -p "$1" && cd "$1" }
extract() {
  if [ -f "$1" ]; then
    case "$1" in
      *.tar.bz2) tar xjf "$1" ;;
      *.tar.gz) tar xzf "$1" ;;
      *.bz2) bunzip2 "$1" ;;
      *.rar) unrar x "$1" ;;
      *.gz) gunzip "$1" ;;
      *.tar) tar xf "$1" ;;
      *.tbz2) tar xjf "$1" ;;
      *.tgz) tar xzf "$1" ;;
      *.zip) unzip "$1" ;;
      *.Z) uncompress "$1" ;;
      *.7z) 7z x "$1" ;;
      *) echo "'$1' cannot be extracted" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
ports() { ss -tulpn | grep LISTEN }
myip() { curl -s ifconfig.me && echo }

# Volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Local bin
export PATH="$HOME/.local/bin:$PATH"

# Zoxide
eval "$(zoxide init zsh)"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Opencode shell integration
if command -v opencode >/dev/null 2>&1; then
  eval "$(opencode shell-env)"
fi

# Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load Powerlevel10k config
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
`

const p10kLeanTemplate = `# Powerlevel10k lean style - Generated by wsl-dev-setup
# Run 'p10k configure' to customize

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
'builtin' 'setopt' 'no_aliases' 'no_param_expand' 'no_prompt_bang' 'no_prompt_percent' 'no_prompt_subst'
'builtin' 'eval' 'p10k_config_opts=("${(@f)$(builtin 'setopt')}")'
'builtin' 'setopt' 'no_aliases' 'no_param_expand' 'no_prompt_bang' 'no_prompt_percent' 'no_prompt_subst'

() {
  emulate -L zsh -o extended_glob
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
}

# The list of segments shown on the left. Fill it with the most important segments.
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
)

# The list of segments shown on the right. Fill it with less important segments.
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  time
)

# Transparent background
typeset -g POWERLEVEL9K_BACKGROUND=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=

# Icon configuration
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=6
typeset -g POWERLEVEL9K_DIR_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=4
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=3
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3

# Status
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1

# Time
typeset -g POWERLEVEL9K_TIME_FOREGROUND=8
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

# Instant prompt
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

'builtin' 'setopt' 'no_aliases' 'no_param_expand' 'no_prompt_bang' 'no_prompt_percent' 'no_prompt_subst'
'builtin' 'eval' '"${p10k_config_opts[@]}"'
'builtin' 'unset' 'p10k_config_opts'
`

const p10kClassicTemplate = `# Powerlevel10k classic style - Generated by wsl-dev-setup
# Run 'p10k configure' to customize

'builtin' 'local' '-a' 'p10k_config_opts'
'builtin' 'setopt' 'no_aliases' 'no_param_expand' 'no_prompt_bang' 'no_prompt_percent' 'no_prompt_subst'
'builtin' 'eval' 'p10k_config_opts=("${(@f)$(builtin 'setopt')}")'
'builtin' 'setopt' 'no_aliases' 'no_param_expand' 'no_prompt_bang' 'no_prompt_percent' 'no_prompt_subst'

() {
  emulate -L zsh -o extended_glob
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
}

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
  newline
  prompt_char
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  time
  newline
  kubecontext
)

typeset -g POWERLEVEL9K_BACKGROUND=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=

typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=6
typeset -g POWERLEVEL9K_DIR_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=4
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=3
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
typeset -g POWERLEVEL9K_TIME_FOREGROUND=8
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=6
typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
  'prod'  'foreground=1'
  'staging' 'foreground=3'
  'dev' 'foreground=2'
)

'builtin' 'setopt' 'no_aliases' 'no_param_expand' 'no_prompt_bang' 'no_prompt_percent' 'no_prompt_subst'
'builtin' 'eval' '"${p10k_config_opts[@]}"'
'builtin' 'unset' 'p10k_config_opts'
`

const p10kRainbowTemplate = `# Powerlevel10k rainbow style - Generated by wsl-dev-setup
# Run 'p10k configure' to customize

'builtin' 'local' '-a' 'p10k_config_opts'
'builtin' 'setopt' 'no_aliases' 'no_param_expand' 'no_prompt_bang' 'no_prompt_percent' 'no_prompt_subst'
'builtin' 'eval' 'p10k_config_opts=("${(@f)$(builtin 'setopt')}")'
'builtin' 'setopt' 'no_aliases' 'no_param_expand' 'no_prompt_bang' 'no_prompt_percent' 'no_prompt_subst'

() {
  emulate -L zsh -o extended_glob
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
}

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
  newline
  prompt_char
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  time
  newline
  kubecontext
)

typeset -g POWERLEVEL9K_MODE='nerdfont-complete'
typeset -g POWERLEVEL9K_BACKGROUND=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=

typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=1
typeset -g POWERLEVEL9K_DIR_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=5
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=6
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=3
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=5
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
typeset -g POWERLEVEL9K_TIME_FOREGROUND=6
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=2
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=3
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=1
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND=1

typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=6

'builtin' 'setopt' 'no_aliases' 'no_param_expand' 'no_prompt_bang' 'no_prompt_percent' 'no_prompt_subst'
'builtin' 'eval' '"${p10k_config_opts[@]}"'
'builtin' 'unset' 'p10k_config_opts'
`

const gitconfigTemplate = `[user]
	name = {{.User}}
	email = {{.Email}}
[core]
	editor = nvim
	pager = delta
	autocrlf = input
[init]
	defaultBranch = main
[delta]
	navigate = true
	light = false
	side-by-side = true
[merge]
	tool = delta
[diff]
	tool = delta
[alias]
	st = status
	co = checkout
	br = branch
	ci = commit
	lg = log --oneline --graph --decorate --all
	ll = log --pretty=format:'%C(yellow)%h %C(blue)%ad %C(red)%d %C(reset)%s %C(green)[%an]' --date=short
	unstage = reset HEAD --
	last = log -1 HEAD
	visual = !gitk
[push]
	autoSetupRemote = true
[pull]
	rebase = false
[fetch]
	prune = true
`